global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "moyo-server"
    static_configs:
      - targets: ["moyo-server:3000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
